# Generated by Django 4.0.5 on 2022-12-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='誕生日'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icon/', verbose_name='プロフィール画像'),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(0, '男性'), (1, '女性')], null=True, verbose_name='性別'),
        ),
        migrations.AddField(
            model_name='user',
            name='userpolicy',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='利用規約'),
        ),
    ]
